// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { Database } from "@/types/database";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

let supabase;

try {
  console.log("Initializing Supabase client...");
  // Access the environment variables using the correct names as defined in the config
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

  console.log("Supabase URL:", supabaseUrl);
  console.log("Supabase Anon Key:", supabaseAnonKey ? "Provided" : "Missing");

  if (!supabaseUrl || !supabaseAnonKey) {
    throw new Error("Missing Supabase environment variables");
  }

  supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storage: typeof window !== "undefined" ? localStorage : undefined,
    },
  });

  // Test the connection
  console.log("Testing Supabase connection...");
  const { data, error } = await supabase.auth.getSession();
  if (error) {
    console.error("Supabase connection test failed:", error);
  } else {
    console.log("Supabase connection test successful");
  }

  console.log("Supabase client initialized successfully");
} catch (error) {
  console.error("Error initializing Supabase client:", error);
  throw error;
}

export { supabase };
